# -*- coding: utf-8 -*-
"""langchain_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMMCYFtUIuGfTOCWni6nr3r_5xdCe4XS
"""

## Integrate our code OpenAI API
import os
from langchain.llms import OpenAI

! pip install langchain_community

## OPENAI LLMS
llm=OpenAI(temperature=0.8, openai_api_key="")

! pip install openai

llm('What is capital Of India')

